config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :applicants
  get 'applicants/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :programs do
      resources :versions do
        resources :postulations do
          resources :tasks do
          end
         collection do
          get 'show_web'
          end
        end
      end
    end
  end


resources :programs
resources :postulations do
  collection do
    get 'final_step'
  end
end
resources :postulation_details
root 'statics#index'

end

app/models/postulation.rb
class Postulation < ActiveRecord::Base
  belongs_to :admin_user
  belongs_to :applicant
  belongs_to :version
  belongs_to :condition, class_name: "PostulationCondition"
  has_many :tasks
  has_one :postulation_detail, dependent: :destroy
  has_one :program, through: :version
  accepts_nested_attributes_for :postulation_detail
end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController
	before_action :set_postulation, only: [:show, :edit, :update, :destroy]
	
	
	def new
		@ultima_postulacion_usuario = Postulation.where(applicant_id: current_applicant.id, version_id: 1).last
		##Si el usuario no tiene una postulacion activa para el programa pasa a una nueva postulacion
		if !@ultima_postulacion_usuario.nil?
			redirect_to final_step_postulations_path
		end	
		@postulation = Postulation.new
		@postulation_details = @postulation.build_postulation_detail
	end

	def create
		@postulation = Postulation.new(postulation_params)
		@postulation.applicant_id = current_applicant.id
		#Se agrea por defecto una version del programa y un administrador
		@postulation.version_id = 1
		@postulation.admin_user_id = 1
		@postulation.condition_id = 4
		@postulation.save
		redirect_to :controller => "postulation_details", :action => "new", :id => @postulation.postulation_detail.id 
	end

	def final_step
		@ultima_postulacion_usuario = Postulation.where(applicant_id: current_applicant.id, version_id: 1).last
	end

	def show
	end

    def edit
	end

	 def update
	 	@postulation.update(postulation_params)
	 	redirect_to final_step_postulations_path, notice: "Campos actualizados"	 	
	 end

	private
		def set_postulation
			@postulation = Postulation.find(params[:id])
		end

		def postulation_params
			params.require(:postulation).permit(:text, postulation_detail_attributes: [:id, :motivation])
		end
end

app/helpers/postulations_helper.rb
module PostulationsHelper
end

app/views/postulations/_form.html.erb
<%= form_for(@postulation, :html => {:class => "form-signin"}) do |f| %>
	<%= f.fields_for :postulation_detail do |pd| %>
	<p class="text-justify">Por favor, cuentanos tu motivacion para tomar nuestro programa</p>
		<%= pd.text_area :motivation, class: "form-control" %>
	<% end %>
</br>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Siguiente paso</button>
	<button class="btn btn-lg btn-success btn-block" type="submit">Guardar Postulacion</button>
<% end %>

app/views/postulations/edit.html.erb
<div class="container">
    <div class="jumbotron">
    <div class="pasos pasos2"></div>
	<%= render 'form' %>
</div>
</div>

app/views/postulations/final_step.html.erb
<div class='container'>
	<div class='jumbotron'>
		<div class="pasos pasos4"></div>

		<h2>Datos Personales</h2>
		<label>Nombre </label>
		<%= current_applicant.name %>
		<label>E-mail </label>
		<%= current_applicant.email %>
		<hr>
		<h2>Datos Postulacion</h2>
		<label>Motivacion </label>
		<%= @ultima_postulacion_usuario.postulation_detail.motivation %>
		</br>
		<%= link_to "Edit", edit_postulation_path(@ultima_postulacion_usuario)%>
		<hr>

		<h2>Lenguajes</h2>
		<% @ultima_postulacion_usuario.postulation_detail.languages.each do |l| %>
			<label>Nombre Idioma</label>
			<%= l.name %>
			<label>Escrito</label>
			<%= l.written_level %>
			<label>Hablado</label>
			<%= l.spoken_level %>
		<% end %>
		</br>
		<%= link_to "Edit", edit_postulation_detail_path(@ultima_postulacion_usuario.postulation_detail)%>
	</div>
</div>

app/views/postulations/new.html.erb
<div class="container">
    <div class="jumbotron">
    <div class="pasos pasos2"></div>
	<%= render 'form' %>
	</div>
</div>