config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :applicants
  get 'applicants/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :programs do
      resources :versions do
        resources :postulations do
          resources :tasks do
          end
         collection do
          get 'show_web'
          end
        end
      end
    end
  end


resources :programs
resources :postulations do
  collection do
    get 'final_step'
  end
end
resources :postulation_details
root 'statics#index'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  #Relaciones
  has_many :postulations, dependent: :destroy
  has_many :tasks, through: :postulations
  belongs_to :condition, class_name: "PostulationCondition"
  #validaciones
  validates :name, :email, :last_name, presence: true
  validates :email, uniqueness: true
      
end

app/controllers/applicants/confirmations_controller.rb
class Applicants::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/applicants/omniauth_callbacks_controller.rb
class Applicants::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/applicants/passwords_controller.rb
class Applicants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/applicants/registrations_controller.rb
class Applicants::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
   end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/applicants/sessions_controller.rb
class Applicants::SessionsController < Devise::SessionsController
 before_filter :configure_sign_in_params, only: [:create]
 #protect_from_forgery :except => :destroy 
  # GET /resource/sign_in
   #def new
     #super
   #end

  # POST /resource/sign_in
   #def create
     #super
   #end

  # DELETE /resource/sign_out
   #def destroy
     #super
   #end

  # protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:signin, :name, :email, :password, :remember_me) }
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
   end
end

app/controllers/applicants/unlocks_controller.rb
class Applicants::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
 #before_filter :authenticate_applicant!, :only => [:index, :new]
 protect_from_forgery except: [:create, :new]
 before_action :set_applicant, only: [:show, :edit, :update, :destroy]
  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    #Crea un nuevo postulante pero todavia no esta en a bdd
    @applicant = Applicant.new(applicant_params)
    #Buscar si exite el postulante
    if Applicant.find_by(email: params[:email])
    puts Applicant.find_by(email: params[:email]).class
            
    end    

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def duplicated_postulation
      return false
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:name, :last_name, :phone, :email)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.erb
<%= bootstrap_form_for(@applicant, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-3") do |f| %>
<% if @applicant.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>
  <ul>
    <% @applicant.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.text_field :name, label: "Nombre Completo", help: "Primer Nombre"  %>
<%= f.text_field :last_name, hide_label: true, help: "Apellido" %>
<%= f.email_field :email, label: "Correo Electrónico",placeholder: "ex:myname@example.com", icon: "envelope"%>
<%= f.telephone_field :phone, label: "Teléfono", help: "022345678 | 0985032654", title: "ej. 022345678 | 0985032654 ", icon: "phone-alt" %>
<%= hidden_field_tag(:program, "3") %>
<%= hidden_field_tag(:version, "Valparaiso") %>
<%= f.form_group do %>
<%= f.submit "Enviar", class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= applicant.name %></td>
        <td><%= applicant.last_name %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.phone %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_applicant_path %>

app/views/applicants/new.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-body">
		<h1 class="text-left">Reserva ya tu cupo!</h1>
		<h3 class="text-left">Asegura tu cupo de <b>manera inmediata</b></h3>
		<hr>
		<%= render 'form' %>
		<%= link_to 'Back', applicants_path %>
		<div>
			<div>
				<div>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applicant.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @applicant.email %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>