config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :applicants
  get 'applicants/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :programs do
      resources :versions do
        resources :postulations do
          resources :tasks do
          end
         collection do
          get 'show_web'
          end
        end
      end
    end
  end


resources :programs
resources :postulations do
  collection do
    get 'final_step'
  end
end
resources :postulation_details
root 'statics#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container-fluid">
		<h4 class="footerleft">
			<a class="btn btn-social-icon btn-twitter"><i class="fa fa-twitter"></i></a> |
			<a class="btn btn-social-icon btn-google-plus"><i class="fa fa-google"></i></a> | 
			<a class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a> 
		</h4>
		<h4 class="footerright text-muted">Bootcamp Latam | Santiago-Chile | 2015</h4>
		<div style="clear: both"></div>
	</div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role"navigation">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">Universidad</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Carreras <span class="caret"></span></a>
          <ul class="dropdown-menu" aria-labelledby="themes">
            <li><a href="../default/">Default</a></li>
          </ul>
        </li>
        <li>
          <a href="../help/">Sedes</a>
        </li>
        <li>
          <a href="http://news.bootswatch.com">Alumnos</a>
        </li><li>
        <a href="http://news.bootswatch.com">Profesores</a>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Postgrados <span class="caret"></span></a>
        <ul class="dropdown-menu" aria-labelledby="download">
          <li><a href="./bootstrap.min.css">bootstrap.min.css</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to Admin, admin_user_session_path%></li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation" >
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
				Aplicacion de Pruebas Rails 4.2
			</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if #user_signed_in? %>
				<p class="navbar-text"> Hola <%= current_user.name %>, estas logeado como: <%= current_user.role %> | <%= link_to("Log out", destroy_user_session_path, method: :delete) %></p>				
				<% else %>
				<p class="navbar-text"><%= #link_to "Sign in", new_user_session_path %></p>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="col-sm-2 sidebar">
	<!-- sidebar content muestra en el titulo como el nombre del controlador actual esto esta seteado en aplication_controller -->
	<ul class="nav nav-sidebar">
		<li class=<%= @controllerName == "User" ? "active" : "" %>><%= link_to 'Usuarios', users_path %></li>
		<li class=<%= @controllerName == "Group" ? "active" : "" %>><%= link_to 'Grupos', groups_path%></li>
		<li class=<%= @controllerName == "Toy" ? "active" : "" %>><%= link_to 'Juguetes', toys_path%></li>
		<li class=<%= @controllerName == "Cymbal" ? "active" : "" %>><%= link_to 'Platillos', cymbals_path%></li>
		<li class=<%= @controllerName == "Task" ? "active" : "" %>><%= link_to 'Tareas', tasks_path%></li>
		<li class=<%= @controllerName == "Cancan" ? "active" : "" %>><%= link_to 'Posts', posts_path%></li>
		<li class=<%= @controllerName == "Party" ? "active" : "" %>><%= link_to 'Parties', parties_path%></li>
		<li class=<%= @controllerName == "Applicanr" ? "active" : "" %>><%= link_to 'Appicants', applicants_path%></li>
	</ul>
</div>

app/views/layouts/_tabs.html.erb
<!--Esto es lo que renderea los flash desde cada uno de los controladores en cualquiera de sus acciones -->
<div class="row">
	<div class="col-xs-12">
		<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end -%>
	</div>
</div>

<!--Esto es lo que renderea los tabs desde cada uno de los controladores en cualquiera de sus acciones -->	
<ul class="nav nav-tabs" role="tablist">
	<li class=<%= @acctionName == "index" ? "active" : "" %>><%= link_to 'View list',
	controller: @controllerName.downcase.pluralize %></li>
	<li class=<%= @acctionName == "new" ? "active" : "" %>><%= link_to "New #{@controllerName.to_s.downcase}",controller: @controllerName.downcase.pluralize, action: 'new' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@controllerName%></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<div class="wrapper">
		<header>
			<%= render 'layouts/navbar'%>
		</header>

		<div class="row">
			<%= yield %>
		</div>
		<%= render 'layouts/footer'%>	
	</div>
</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @controllerName %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

<body>
	<div id="main-container" class="container-fluid">
			<%= render 'layouts/navigation'%>
		<div class="row">
			<%= render 'layouts/sidebar'%>
			<div id="content" class="col-sm-10">
				<%= render 'layouts/tabs'%>
				<%= yield %>
			</div>
		</div>
	</div>	
</body>
</html>